failed test-build job

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -8,9 +8,8 @@ on:
     branches: [main]
     types: [opened, synchronize]
 
-
 jobs:
-  simple_deployment_pipeline:
+  test-build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v6
@@ -33,26 +32,67 @@ jobs:
         run: npx playwright install --with-deps
       - name: Run Playwright tests
         run: npm run test:e2e
-
+      - name: try to fail 
+        run: exit 1
       - uses: actions/upload-artifact@v4
         if: ${{ !cancelled() }}
         with:
           name: playwright-report
           path: playwright-report/
           retention-days: 30
-      
-      - name: try to fail 
-        run: exit 1
 
+  # simple_deployment_pipeline:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v6
+  #     - uses: actions/setup-node@v6
+  #       with:
+  #         node-version: '24'
+  #     - name: Install dependencies 
+  #       run: npm ci 
+
+  #     - name: Check style        
+  #       run: npm run eslint
+
+  #     - name: Run npm test
+  #       run: npm run test
+
+  #     - name: Run npm run build
+  #       run: npm run build
+
+  #     - name: Install Playwright Browsers
+  #       run: npx playwright install --with-deps
+  #     - name: Run Playwright tests
+  #       run: npm run test:e2e
+
+  #     - uses: actions/upload-artifact@v4
+  #       if: ${{ !cancelled() }}
+  #       with:
+  #         name: playwright-report
+  #         path: playwright-report/
+  #         retention-days: 30
+      
+  #     - name: try to fail 
+  #       run: exit 1
+
+  #     - name: Deploy
+  #       if: github.ref == 'refs/heads/main' && github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip')
+  #       env:
+  #         deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
+  #       run: |
+  #         curl "$deploy_url"     
+  deploy:
+    needs: [test-build]
+    runs-on: ubuntu-latest
+    steps: 
       - name: Deploy
         if: github.ref == 'refs/heads/main' && github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip')
         env:
           deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
         run: |
           curl "$deploy_url"     
-      
   tag_release:
-    needs: [simple_deployment_pipeline]
+    needs: [deploy,test-build]
     runs-on: ubuntu-latest
     if: ${{ contains( join( github.event.commits.*.message, ', '), '#skip' ) == false }}
     steps:
@@ -66,10 +106,23 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   notify: 
-      needs: [simple_deployment_pipeline]
+      needs: [test-build,deploy]
       runs-on: ubuntu-latest
       if: always()
       steps:
+      - name: Find failed jobs
+        id: failed_jobs
+        run: |
+          echo '${{ toJson(needs) }}' > needs.json
+
+          FAILED_JOBS=$(jq -r '
+            to_entries
+            | map(select(.value.result == "failure" or .value.result == "cancelled"))
+            | .[].key
+          ' needs.json | paste -sd ", " -)
+
+          echo "failed_jobs=$FAILED_JOBS" >> $GITHUB_OUTPUT
+
       - name: err_msg 
         uses: sarisia/actions-status-discord@v1
         if: ${{ needs.simple_deployment_pipeline.result == 'failure' || needs.simple_deployment_pipeline == 'cancelled' }}
@@ -87,7 +140,7 @@ jobs:
             **Message**: `${{ github.event.commits[0].message }}`
             **Author**: `${{ github.event.commits[0].author.name }}`
             **Workflow**: `${{ github.workflow }}`
-            **Job**: `${{ github.job }}`
+            **Job**: `${{ steps.failed_jobs.outputs.failed_jobs }}`
 
             [View Commit](${{ github.event.commits[0].url }})
             [View Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}})
