backward

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -8,31 +8,29 @@ on:
     branches: [main]
     types: [opened, synchronize]
 
+
 jobs:
-  test_build:
+  simple_deployment_pipeline:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
-
-      - uses: actions/setup-node@v4
+      - uses: actions/checkout@v6
+      - uses: actions/setup-node@v6
         with:
-          node-version: "24"
+          node-version: '24'
+      - name: Install dependencies 
+        run: npm ci 
 
-      - name: Install dependencies
-        run: npm ci
-
-      - name: Check style
+      - name: Check style        
         run: npm run eslint
 
-      - name: Run tests
+      - name: Run npm test
         run: npm run test
 
-      - name: Build
+      - name: Run npm run build
         run: npm run build
 
       - name: Install Playwright Browsers
         run: npx playwright install --with-deps
-
       - name: Run Playwright tests
         run: npm run test:e2e
 
@@ -43,84 +41,150 @@ jobs:
           path: playwright-report/
           retention-days: 30
 
-  deploy:
-    needs: test_build
-    runs-on: ubuntu-latest
+      - name: skip commit 
+        if: ${{ contains( join( github.event.commits.*.message, ', '), '#skip' ) == false }}
+        run: echo 'Valid commit'
 
-    if: >
-      github.ref == 'refs/heads/main' &&
-      github.event_name == 'push' &&
-      !contains(join(github.event.commits.*.message, ', '), '#skip')
-
-    steps:
-      - name: deploy
+      - name: Deploy
+        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip')
         env:
           deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
-        run: curl "$deploy_url"
+        run: |
+          curl "$deploy_url"     
 
-  tag_release:
-    needs: deploy
-    runs-on: ubuntu-latest
-
-    if: ${{ !contains(join(github.event.commits.*.message, ', '), '#skip') }}
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - name: Bump version and push tag
-        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-  discord_msg:
-    runs-on: ubuntu-latest
-    needs: deploy
-    if: always()
-
-    steps:
-      - name: failed msg
+      - name: The job has failed
         uses: sarisia/actions-status-discord@v1
-        if: ${{ needs.deploy.result == 'failure' || needs.deploy.result == 'cancelled' }}
+        if: ${{ failure() }}
         with:
           webhook: ${{ secrets.DISCORD_WEBHOOK }}
           status: ${{ job.status }}
           nodetail: true
           username: Fullstack part 11 Hook
-          content: ":x: Build failed! The pipeline encountered an error"
+          content: " :x: Build failed! The pipeline encountered an error"
           title: "Failure details"
           description: |
-            **Repo**: `${{ github.repository }}`
-            **Branch**: `${{ github.ref_name }}`
-            **Commit**: `${{ github.sha }}`
-            **Message**: `${{ github.event.head_commit.message }}`
-            **Author**: `${{ github.event.head_commit.author.name }}`
-            **Workflow**: `${{ github.workflow }}`
-            **Job**: `${{ github.job }}`
+            **Repo**: ${{ github.repository }}
+            **Branch**: ${{ github.ref_name }}
+            **Commit**: ${{ github.sha }}
+            **Message**: ${{ github.event.commits.message }}
+            **Author**: ${{ github.event.commits.author.name }}
+            **Workflow**: ${{ github.workflow }}
+            **Job**: ${{ github.job }}
 
-            [View Commit](${{ github.event.head_commit.url }})
-            [View Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
+            [View Commit](${{ github.event.commits[0].url }})
+
+            View Workflow Run:
+            <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}>
 
           image: ${{ secrets.EMBED_IMAGE }}
           color: 0xff0000
+      
+  tag_release:
+    needs: [simple_deployment_pipeline]
+    runs-on: ubuntu-latest
+    if: ${{ contains( join( github.event.commits.*.message, ', '), '#skip' ) == false }}
+    steps:
+     - name: Checkout repository
+       uses: actions/checkout@v4
+       with:
+          fetch-depth: 0
+     - name: try to fail 
+       run: exit 1
 
-      - name: success msg
-        uses: sarisia/actions-status-discord@v1
-        if: ${{ needs.deploy.result == 'success' }}
-        with:
+     - name: Bump version and push tag
+       uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
+       env: 
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+     - name: The job has succeeded
+       uses: sarisia/actions-status-discord@v1
+       if: ${{ success() }}
+       with:
           webhook: ${{ secrets.DISCORD_WEBHOOK }}
           status: ${{ job.status }}
           nodetail: true
           username: Fullstack part 11 Hook
           color: 0x00ff00
-          content: ":white_check_mark: Deployment Successful!"
-          title: "Deployment Details"
-          description: |
+          content: ":white_check_mark:  Deployement Successful! A new version deployed to production"
+          title: "Deployement Details"
+          description: | 
             **Commit**: `${{ github.sha }}`
-            **Message**: `${{ github.event.head_commit.message }}`
-            **Author**: `${{ github.event.head_commit.author.name }}`
+            **Message**: `${{ github.event.commits[0].message }}`
+            **Author**: `${{ github.event.commits[0].author.name }}`
 
           url: "https://github.com/sarisia/actions-status-discord"
           avatar_url: ${{ secrets.AVATAR_URL }}
+
+     - name: The job has failed
+       uses: sarisia/actions-status-discord@v1
+       if: ${{ failure() || cancelled()   }}
+       with:
+          webhook: ${{ secrets.DISCORD_WEBHOOK }}
+          status: ${{ job.status }}
+          nodetail: true
+          username: Fullstack part 11 Hook
+          content: " :x: Build failed! The pipeline encountered an error"
+          title: "Failure details"
+          description: |
+            **Repo**: `${{ github.repository }}`
+            **Branch**: `${{ github.ref_name }}`
+            **Commit**: `${{ github.sha }}`
+            **Message**: `${{ github.event.commits[0].message }}`
+            **Author**: `${{ github.event.commits[0].author.name }}`
+            **Workflow**: `${{ github.workflow }}`
+            **Job**: `${{ github.job }}`
+
+            [View Commit](${{ github.event.commits[0].url }})
+            [View Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}}
+
+          image: ${{ secrets.EMBED_IMAGE }}
+          color: 0xff0000
+
+  # discord_msg:
+  #   needs: [simple_deployment_pipeline]
+  #   if: ${{ always() }}
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: The job has succeeded
+  #       uses: sarisia/actions-status-discord@v1
+  #       if: ${{ success() }}
+  #       with:
+  #         webhook: ${{ secrets.DISCORD_WEBHOOK }}
+  #         status: ${{ job.status }}
+  #         nodetail: true
+  #         username: Fullstack part 11 Hook
+  #         color: 0x00ff00
+  #         content: ":white_check_mark:  Deployement Successful! A new version deployed to production"
+  #         title: "Deployement Details"
+  #         description: | 
+  #           **Commit**: `${{ github.sha }}`
+  #           **Message**: `${{ github.event.commits[0].message }}`
+  #           **Author**: `${{ github.event.commits[0].author.name }}`
+
+  #         url: "https://github.com/sarisia/actions-status-discord"
+  #         avatar_url: ${{ secrets.AVATAR_URL }}
+      
+  #     - name: The job has failed
+  #       uses: sarisia/actions-status-discord@v1
+  #       if: ${{ failure() }}
+  #       with:
+  #         webhook: ${{ secrets.DISCORD_WEBHOOK }}
+  #         status: ${{ job.status }}
+  #         nodetail: true
+  #         username: Fullstack part 11 Hook
+  #         content: " :x: Build failed! The pipeline encountered an error"
+  #         title: "Failure details"
+  #         description: |
+  #           **Repo**: `${{ github.repository }}`
+  #           **Branch**: `${{ github.ref_name }}`
+  #           **Commit**: `${{ github.sha }}`
+  #           **Message**: `${{ github.event.commits.message }}`
+  #           **Author**: `${{ github.event.commits.author.name }}`
+  #           **Workflow**: `${{ github.workflow }}`
+  #           **Job**: `${{ github.job }}`
+
+  #           [View Commit](${{ github.event.commits.url }})
+  #           [View Workflow Run](https://github.com/${{ github.repository }})/actions/runs/${{ github.run_id}}
+
+  #         image: ${{ secrets.EMBED_IMAGE }}
+  #         color: 0xff0000
