failed test-build job

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -32,7 +32,8 @@ jobs:
         run: npx playwright install --with-deps
       - name: Run Playwright tests
         run: npm run test:e2e
-      - name: try to fail 
+
+      - name: mock failed job
         run: exit 1
       - uses: actions/upload-artifact@v4
         if: ${{ !cancelled() }}
@@ -85,6 +86,8 @@ jobs:
     needs: [test-build]
     runs-on: ubuntu-latest
     steps: 
+      # - name: try to fail 
+      #   run: exit 1
       - name: Deploy
         if: github.ref == 'refs/heads/main' && github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip')
         env:
@@ -125,7 +128,12 @@ jobs:
 
       - name: err_msg 
         uses: sarisia/actions-status-discord@v1
-        if: ${{ needs.simple_deployment_pipeline.result == 'failure' || needs.simple_deployment_pipeline == 'cancelled' }}
+        if: | 
+          needs.deploy.result == 'failure' ||
+          needs.test-build.result == 'failure' ||
+          needs.deploy.result == 'cancelled' ||
+          needs.test-build.result == 'cancelled' 
+
         with:
           webhook: ${{ secrets.DISCORD_WEBHOOK }}
           status: ${{ job.status }}
